### ISSUE TITLE
Improve rate of blocking

### ISSUE THREAD

**Issue by metalwarrior665** [gippy/instagram-scraper#121]
Current problems:

- Residential proxy must be used, on datacenters it fails almost 100% of time
- Even residentials fail to launch the page (redirected to login) once a few runs
- Scrolling is often "blocked" with 302 status (maybe slowing down would help?)

**Comment by loweas** [comment]
So, I don't have any solutions but wanted to join the conversation. I think this just happened to me. I'm trying to scrape historical location pages just to get the count and day of upload. I think I got blocked using residential proxies and all that. It worked for the first few (though didn't collect all the post that said it contained). Anyhoos, very bummed about it because I think I have just about 30 more locations that shouldn't have much content. If there is any advice for decreasing the likelihood of banning like wait for scroll to 100000 seconds or something and again I just join the conversation in general.

**Comment by pocesar** [comment]
datacenter + login cookies should suffice
