### ISSUE TITLE
Crashed after ~4000 Items from Instagram post data / Scrolling error

### ISSUE THREAD

**Issue by kk-Chiron** [gippy/instagram-scraper#22]
@gippy 
Error:
```
2020-02-10T11:30:30.967Z ERROR: TypeError: Cannot read property 'hashtag' of undefined
2020-02-10T11:30:41.893Z INFO: Tag "HASHTAG": Retry scroll after 4 seconds
2020-02-10T11:30:55.907Z INFO: Tag "HASHTAG": Retry scroll after 9 seconds
2020-02-10T11:31:14.915Z INFO: Tag "redaesthetics": Retry scroll after 16 seconds
```

There is an inbuild scroll limit with Instagram hashtags
Please fix

**Comment by metalwarrior665** [comment]
The issue is this is running in one browser tab, no pagination. And from what I know, Instagram will not allow us to "continue" this infinite scroll even with specific parameters. So this might be also hitting the maximum for a browser or Instagram.

Anyway, we need to test this properly and document if such a limit exists.

**Comment by metalwarrior665** [comment]
So I was testing this a lot lately and while there is a possibility for an infinite scroll, it starts to get really slow around 500+ posts. I think you can get even over 4000 comments but it will require a lot of time and might crash for different reasons because it is hard to properly test.

Anyway, I plan to do more testing here.

**Comment by pocesar** [comment]
DOM elements are removed as they load, should not crash anymore (tested with 80k items)
