### ISSUE TITLE
Scraping large number of posts and comments of hashtag

### ISSUE THREAD

**Issue by benjibee** [gippy/instagram-scraper#94]
I'm attempting to collect some data for a friend writing a research paper. I'm trying to scrape all posts and comments for the hastag [#drumkits](https://www.instagram.com/explore/tags/drumkits/) and save them to a CSV. Running an agent with the following setup returns only about 200 posts before stopping, though there's over 60,000 for this tag.

```json
 "search": "drumkits",
  "searchType": "hashtag",
  "searchLimit": 100,
  "resultsType": "posts",
  "scrollWaitSecs": 30,
  "proxy": {
    "useApifyProxy": true,
    "apifyProxyGroups": [
      "RESIDENTIAL"
    ]
  },
```

There are also quite a few errors saying ` failed 6 times, not retrying any more` for posts or pages that are working otherwise. The comments for posts are also not collected, it seems.

 I've read over a lot of issues on here and read through the documentation a few times, so I hope there's not something simple I'm missing. But any help getting this working would save me a lot of headaches!

**Comment by metalwarrior665** [comment]
Thanks for submitting this issue. Usually, the limit for a single scroll (single tag) is around 5000 posts before Instagram cuts you off. We have a clue how to improve this number so hopefully, in the future, this limitation will be off.

Your input is even more complicated because `searchLimit: 100` means it will scrape also 100 similar hashtags and scroll for each of them. You might have overwhelmed the site a bit but in general it should be fine.

The direct problem is that if you don't specify `resultsLimit` field at all, it will limit to 200. So just pass in `resultsLimit: 99999`. We will probably remove this internal default.

**Comment by metalwarrior665** [comment]
I tried it and scraped `4707/64457` posts for just `drumkits`.

**Comment by benjibee** [comment]
Okay, thanks for the tips. I think I was confused by how `searchLimit` and `resultsLimit` modify the request. For the research it doesn't work so well if we can't sample the full results of the hashtag, however. So I'll keep an eye on this repo, and if I could be of help testing anything I'd be happy to.
